### ISSUE TITLE
sqlite3.OperationalError: 3 values for 2 columns

### ISSUE THREAD

**Issue by neozerosv** [neozerosv/invernadero-pi#2]
venv) pi@raspberrypi:~/invernadero-pi $ flask init-db
/home/pi/invernadero-pi/instance/invernadero.sqlite
Traceback (most recent call last):
  File "/home/pi/invernadero-pi/venv/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/home/pi/invernadero-pi/venv/lib/python3.7/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/home/pi/invernadero-pi/venv/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/pi/invernadero-pi/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/pi/invernadero-pi/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/invernadero-pi/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/invernadero-pi/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/invernadero-pi/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/invernadero-pi/venv/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/pi/invernadero-pi/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/invernadero-pi/piinvernadero/db.py", line 52, in init_db_command
    init_db()
  File "/home/pi/invernadero-pi/piinvernadero/db.py", line 44, in init_db
    db.executescript(f.read().decode('utf8'))
sqlite3.OperationalError: 3 values for 2 columns

**Comment by neozerosv** [comment]
pi@raspberrypi:~/invernadero-pi $ git diff ./piinvernadero/schema.sql
diff --git a/piinvernadero/schema.sql b/piinvernadero/schema.sql
index 54fb1a8..db5ccc1 100644
--- a/piinvernadero/schema.sql
+++ b/piinvernadero/schema.sql
@@ -4,7 +4,8 @@ DROP TABLE IF EXISTS site;
 DROP TABLE IF EXISTS sensor;
 DROP TABLE IF EXISTS actuator;
 DROP TABLE IF EXISTS alert;
-DROP TABLE IF EXISTS invernadero1;
+DROP TABLE IF EXISTS sitetableinvernadero1;
+DROP TABLE IF EXISTS sitetableinvernadero2;
 
 CREATE TABLE grupo (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
@@ -29,8 +30,8 @@ CREATE TABLE site (
   address INTEGER NOT NULL,
   description TEXT NOT NULL
 );
-INSERT INTO site(name,description) VALUES('invernadero1',201,'Invernadero 1');
-INSERT INTO site(name,description) VALUES('invernadero2',202,'Invernadero 2');
+INSERT INTO site(name,address,description) VALUES('invernadero1',201,'Invernadero 1');
+INSERT INTO site(name,address,description) VALUES('invernadero2',202,'Invernadero 2');
 
 
 CREATE TABLE sensor (
